### ISSUE TITLE
Opentelemetry

### ISSUE THREAD

**Issue by prody1605** [qclaogui/codelab-monitoring#167]
Hello, working with Opentelemetry java agent?
Thanks

**Comment by qclaogui** [comment]
By default, the OpenTelemetry Java agent uses [OTLP exporter](https://github.com/open-telemetry/opentelemetry-java/tree/main/exporters/otlp). Just to send data to [Grafana Alloy](https://github.com/open-telemetry/opentelemetry-collector/blob/main/receiver/otlpreceiver/README.md) at `OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"`.  See: https://github.com/qclaogui/codelab-monitoring/blob/11531c3594d93ea2dd7e4f781c0156bf0482b37d/alloy-modules/compose/traces/process-and-transform.alloy#L63
Here is a similar example: https://github.com/qclaogui/codelab-monitoring/blob/11531c3594d93ea2dd7e4f781c0156bf0482b37d/examples/grafana-beyla/compose.yaml#L35

**Comment by qclaogui** [comment]
Hi @prody1605, just found opentelemetry-java-examples https://github.com/open-telemetry/opentelemetry-java-examples/blob/d740b00e31e8f8520560273860b4cd651e5fb31c/javaagent/docker-compose.yml#L7

we can do some change in `docker-compose.yml`:

## Try it

```shell
git clone https://github.com/open-telemetry/opentelemetry-java-examples && cd "$(basename "$_" .git)"
```

```shell
cd javaagent && ../gradlew bootJar
```

Replace `docker-compose.yml` with the following:
```yaml
include:
- path: https://github.com/qclaogui/codelab-monitoring.git#main:docker-compose/monolithic-mode/traces/compose.yaml

services:
  app:
    build: ./
    environment:
      OTEL_SERVICE_NAME: "agent-example-app"
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://alloy:4318"
    ports:
      - "8080:8080"

```

```shell
COMPOSE_EXPERIMENTAL_GIT_REMOTE=true docker compose up -d --remove-orphans
```

Once all containers are up and running you can search for traces in Grafana.

Navigate to [http://localhost:3000](http://localhost:3000)
