### ISSUE TITLE
Simple use case

### ISSUE THREAD

**Issue by qclaogui** [qclaogui/codelab-monitoring#67]
An simple use case like so:

```yaml
cat <<EOF > compose.yaml
# include is available in Docker Compose version 2.20 and later, and Docker Desktop version 4.22 and later.
include:
- path: https://github.com/qclaogui/codelab-monitoring.git#main:docker-compose/monolithic-mode/logs/compose.yaml

# https://github.com/qclaogui/codelab-monitoring/blob/main/docker-compose/common/config/agent-flow/modules/docker/README.md
services:
  github-exporter:
    image: githubexporter/github-exporter:latest
    environment:
    - REPOS=qclaogui/codelab-monitoring
EOF
```

```shell
COMPOSE_EXPERIMENTAL_GIT_REMOTE=true docker compose pull
```

run:

```shell
COMPOSE_EXPERIMENTAL_GIT_REMOTE=true docker compose up -d --remove-orphans
```

Once all containers are up and running you can search for logs(from Loki) in Grafana. 

> In this case you can find `github-exporter` metrics and logs.

Navigate to [http://localhost:3000](http://localhost:3000)

### CHECKLISTS
- [ ] Add support `publish` (alpha) command. See: https://github.com/docker/compose/pull/10949#issuecomment-1935870462

- [x] More docs added.
